### PR TITLE
[WIP] Changes for explicit solvent host-guest unbinding

### PR DESCRIPTION
**Pull request by jchodera**
- Added initial equilibration to try to avoid `nan`s

### CODE REVIEW

**Comment by jchodera** [comment]
I'm seeing some failures with the latest master head of openpathsampling on the ligand unbinding host-guest system in explicit solvent:

```
Working on Bootstrapping cycle step 128 in ensemble 1/49 .
Working on Bootstrapping cycle step 129 in ensemble 1/49 .
Working on Bootstrapping cycle step 130 in ensemble 1/49 .
Working on Bootstrapping cycle step 131 in ensemble 1/49 .
Working on Bootstrapping cycle step 132 in ensemble 1/49 .
Traceback (most recent call last):
  File "setup-ops.py", line 231, in <module>
    initial_sample_set = bootstrap.run()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathsimulator.py", line 456, in run
    bootstrap.run(n_steps_per_round)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathsimulator.py", line 262, in run
    movepath = bootstrapmove.move(self.sample_set)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 2385, in move
    subchange = self.mover.move(sample_set)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 1922, in move
    mover.move(sample_set),
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 2245, in move
    movepath = mover.move(subglobal)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 1922, in move
    mover.move(sample_set),
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 1108, in move
    trials = self(*samples)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 1200, in __call__
    trial_trajectory = self._run(initial_trajectory, shooting_index)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 1275, in _run
    trajectory, shooting_index
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 1239, in _make_forward_trajectory
    running=[run_f])
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/engines/dynamics_engine.py", line 361, in generate
    snapshot = self.generate_next_frame()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/engines/openmm/engine.py", line 259, in generate_next_frame
    return self.current_snapshot
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/engines/openmm/engine.py", line 228, in current_snapshot
    self._current_snapshot = self._build_current_snapshot()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/engines/openmm/engine.py", line 218, in _build_current_snapshot
    raise ValueError('No attribute' + str(e))
ValueError: No attribute'module' object has no attribute 'Dataframe'
Tue Aug 16 17:28:31 EDT 2016
Compute mode is already set to DEFAULT for GPU 0000:03:00.0.
All done.
```

**Comment by jchodera** [comment]
Hm. I think some recent change must have broken ops. I keep running into this error:

```
Working on Bootstrapping cycle step 291 in ensemble 1/49 .
Working on Bootstrapping cycle step 292 in ensemble 1/49 .
Traceback (most recent call last):
  File "setup-ops.py", line 231, in <module>
    initial_sample_set = bootstrap.run()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathsimulator.py", line 456, in run
    bootstrap.run(n_steps_per_round)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathsimulator.py", line 262, in run
    movepath = bootstrapmove.move(self.sample_set)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 2385, in move
    subchange = self.mover.move(sample_set)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 1922, in move
    mover.move(sample_set),
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 2245, in move
    movepath = mover.move(subglobal)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 1922, in move
    mover.move(sample_set),
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 1108, in move
    trials = self(*samples)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 1200, in __call__
    trial_trajectory = self._run(initial_trajectory, shooting_index)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 1279, in _run
    trajectory, shooting_index
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/pathmover.py", line 1250, in _make_backward_trajectory
    running=[run_f])
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/engines/dynamics_engine.py", line 361, in generate
    snapshot = self.generate_next_frame()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/engines/openmm/engine.py", line 259, in generate_next_frame
    return self.current_snapshot
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/engines/openmm/engine.py", line 228, in current_snapshot
    self._current_snapshot = self._build_current_snapshot()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/engines/openmm/engine.py", line 218, in _build_current_snapshot
    raise ValueError('No attribute' + str(e))
ValueError: No attribute'module' object has no attribute 'Dataframe'
```

**Comment by jhprinz** [comment]
> ValueError: No attribute'module' object has no attribute 'Dataframe'

This is `NaN` again falsely interpreted. At least I am pretty sure.

**Comment by dwhswenson** [comment]
@jhprinz: Why are you converting the `AttributeError` to a `ValueError` there? In fact, why do we need any of that `try: except:` block? It looks like all it is doing is obscuring the original source of the error. Was this old debugging stuff that might be best to remove now?

**Comment by dwhswenson** [comment]
@jchodera : to clarify what I meant by "use a storage with the bootstrapping" (https://github.com/openpathsampling/openpathsampling/issues/558#issuecomment-240217668) -- I meant to add some `storage=my_storage` argument to the setup of `FullBootstrapping`. It looks like you tried to save the `FullBootstrapping` object -- which should work, but doesn't accomplish anything useful.

The difference is between saving a _description of the simulation_ you plan to do (replacing the need to rewrite a script to build it) and saving the _results_ of that simulation. `storage.save(bootstrap)` does the former. `bootstrap = FullBootstrapping(..., storage=storage)` does the latter.

BTW: you _can_ save trajectories from the bootstrapping and the actual TIS simulation to the same file, and separate them later by identifying looking at the `MoveChange` of each. But personally, I find it easier to keep the results from unrelated simulation types in separate files.

**Comment by jchodera** [comment]
> The difference is between saving a description of the simulation you plan to do (replacing the need to rewrite a script to build it) and saving the results of that simulation. storage.save(bootstrap) does the former. bootstrap = FullBootstrapping(..., storage=storage) does the latter.

Thanks!  Maybe the docs on storage would be a good place to mention this?

http://openpathsampling.org/latest/examples/storage.html

**Comment by dwhswenson** [comment]
Hmm... a couple of times you've made comments that suggest that what you're expecting from the docs on storage are very different from what was written.

The storage example you point to is mainly aimed at showing the features of @jhprinz's netcdfplus subpackage. You can store and reload arbitrary objects, and they store the things inside them. You can name objects and reload them by name. But the examples he uses are things you're unlikely to do for practical path sampling.

You're looking for a more practical usage case. I think the way the docs look now are misleading, and that's causing confusion. Honestly, at this point, I'd say you should ignore everything on openpathsampling.org, and stick to current versions of the example notebook (reorg of directory structure on that coming soon -- I plan to open the PR today, although it won't be done until a few other PRs get merged.) What you want should be shown in various `_analysis` notebooks, or read the TPS analysis section of Paper I, which tries to introduce most of the major ideas.

In practice, you really shouldn't have to interact with storage very much. If you're creating a new simulation based on an old one, you reload the states, etc., instead of recreating them. When you do analysis, you load the main objects (`scheme` so far, but actually, I think we should move to saving/reloading the `PathSimulator` in our examples) and then send `storage.steps` as input to analysis.

You will almost never directly load trajectories, or snapshots, or anything else like that, because you mainly care about them in the context you get from the `step` (was this trajectory accepted? what ensemble was it a sample from?).

Overall: yes, docs need major work.

**Comment by jchodera** [comment]
Ah, OK! Thanks so much for the clarification!

**Comment by jhprinz** [comment]
> Why are you converting the AttributeError to a ValueError there? @jchodera 

Well, that is some python specific problem. Let me try to explain it ina nutshell:

If you use a descriptor, e.g. a `@property` then accessing this property it the python internal implementation (in `__getattr__`) will wrap the call of the property with a try catch for AttributeError.
If that error occurs it returns that the attribute does not exists. The idea is to catch calls to non-existant properties and return the AttributeError as if you would have tried to access a regular attribute.

Now the problem. If for another reason during the execution of the code pf the property an `AttributeError` is raised, you get again the `object has no attribute xyz`, disregarding
of the actual error occurred. For any other error this works fine though. So we catch AttribtueErrors and then explicitely call the property getter to circumvent the AttributeError catch.

**Comment by jhprinz** [comment]
Agreed, we should have a better storage tutorial. There is actually a rudimentary storage tutorial but it is more on how to work with the file format than the specifics on working with ops objects in storage.

**Comment by dwhswenson** [comment]
>  you use a descriptor, e.g. a `@property` then accessing this property it the python internal implementation (in `__getattr__`) will wrap the call of the property with a try catch for AttributeError.

Yes, but didn't we fix this in https://github.com/openpathsampling/openpathsampling/pull/516? Can't this be removed now?

**Comment by jhprinz** [comment]
Correct. I was explaining our fix. I did not see, that there was still another wrapper in place in openmm.engine. We should indeed remove that.

**Comment by dwhswenson** [comment]
@jhprinz : I think we're talking past each other, and I think you thought _my_ comment came from @jchodera (rereading your explanation, you explained what I did in the PR I linked to).

I was looking at @jchodera's error, which is at line https://github.com/openpathsampling/openpathsampling/blob/master/openpathsampling/engines/openmm/engine.py#L218

Here you're catching an `AttributeError` and remapping it to `ValueError`. This also means that we no longer have the actual traceback for the problem.

However, reading the error message, it suggests to me that someone made a typo when they did something with a pandas dataframe, probably typing `pd.Dataframe` instead of `pd.DataFrame`. ('module' in the error message being `pandas`.)

```
$ grep -n "pd.Dataframe" **/*py
engines/features/shared.py:60:                    df=str(pd.Dataframe(coords)) + "\n"
```

That looks like the error to me. My mistake in https://github.com/openpathsampling/openpathsampling/commit/4d20d6b0 -- it _is_ the NaN problem; this was supposed to output a pandas frame to show you exactly where the NaN happened.

I can remove those wrappers and fix the actual error in a quick PR, unless you'd prefer to do so. Does it make sense to output that dataframe? Maybe that's a bit much....

**Comment by jhprinz** [comment]
I like the idea of some more detail on where the NaN occurs. Maybe the full dataframe is not necessary. What about return the pdb as a text. This would allow a user to see the topological context and hint to problems of the setup (insufficient equilibration, FF problems, etc.)

Using mdtraj that should be easy.

**Comment by dwhswenson** [comment]
Even so, that would be pretty large, right? If you have, say 22k atoms for a protein in water?

What I did in https://github.com/openpathsampling/openpathsampling/pull/567 was to report the atom index of anything with NaN coordinates. I thought that might be enough that a user could then explore further on their own, without creating a huge screen of text.

**Comment by jhprinz** [comment]
True, maybe then only the lines if the pdb that contain `NaNs` (not even sure if mdtraj can convert a frame nans to a pdb. It was just an idea on what might help a user best to quickly solve the problem. The atom coordinates alone still require figuring out, what these atoms are. We could have a function in the topology to return a string description. It could be useful for other purposes.

For now just fixing the DataFrame would be fine.

**Comment by jchodera** [comment]
Just a reminder that we still absolutely need a way to reject NaNs and
carry on with simulations in order for this to be at all usable. I agree
that better reporting the NaNs is helpful, but that won't actually fix
anything to the point of making it useful for real systems.

**Comment by jhprinz** [comment]
I have a PR ready but not pushed that will address this. You can change the behaviour of an engine to your liking. I requires the Ala PR to be merged first since this will make some changes to engine as well.

**Comment by jchodera** [comment]
Awesome!

**Comment by jchodera** [comment]
Rerunning with `VVVRIntegrator` and fresh install of `master`...

**Comment by jchodera** [comment]
@jhprinz @dwhswenson : Did `populate_minus_ensemble_from_set` change names?

```
DONE! Completed Bootstrapping cycle step 2525 in ensemble 46/49.
Working on Bootstrapping cycle step 2526 in ensemble 46/49 .
Working on Bootstrapping cycle step 2527 in ensemble 47/49 .
Working on Bootstrapping cycle step 2528 in ensemble 47/49 .
Working on Bootstrapping cycle step 2529 in ensemble 48/49 .
Working on Bootstrapping cycle step 2530 in ensemble 48/49 .
Working on Bootstrapping cycle step 2531 in ensemble 48/49 .
Working on Bootstrapping cycle step 2532 in ensemble 48/49 .
DONE! Completed Bootstrapping cycle step 2532 in ensemble 49/49.
[Trajectory[6], Trajectory[5], Trajectory[7], Trajectory[8], Trajectory[7], Trajectory[9], Trajectory[8], Trajectory[13], Trajectory[11], Trajectory[11], Trajectory[10], Trajectory[12], Trajectory[16], Trajectory[17], Trajectory[14], Trajectory[16], Trajectory[21], Trajectory[22], Trajectory[26], Trajectory[24], Trajectory[28], Trajectory[29], Trajectory[26], Trajectory[33], Trajectory[31], Trajectory[34], Trajectory[65], Trajectory[113], Trajectory[116], Trajectory[84], Trajectory[96], Trajectory[95], Trajectory[98], Trajectory[97], Trajectory[170], Trajectory[355], Trajectory[329], Trajectory[521], Trajectory[698], Trajectory[580], Trajectory[937], Trajectory[304], Trajectory[1016], Trajectory[534], Trajectory[1024], Trajectory[1011], Trajectory[633], Trajectory[664], Trajectory[664]]
Missing ensembles:
*  [[MinusInterfaceEnsemble]]
No extra ensembles.

Populating the minus ensemble
Traceback (most recent call last):
  File "setup-ops.py", line 247, in <module>
    samp = minus.populate_minus_ensemble_from_set(
AttributeError: 'MinusInterfaceEnsemble' object has no attribute 'populate_minus_ensemble_from_set'
```

The good news is that we didn't run into any `NaN`s during bootstrapping, though!

**Comment by dwhswenson** [comment]
Yeah, the name on that changed. You can see current usage in the MSTIS toy example, `mstis.ipynb`. (Replying from mobile now, so I can't easily point to the exact differences.)

@jhprinz has tried to put everything for assigning initial trajectories to ensembles into one function. There are some limitations on that, although it should work for this case. I'm not entirely sure what the syntax for that is, but I'm sure he can explain!

**Comment by jhprinz** [comment]
A quick note, that the most recent PR introduced some changes in storage / json pickling which will prevent loading older files.

**Comment by jchodera** [comment]
Thanks!

How would we load from storage and resume the path sampling simulation? I
don't actually have a script to do that yet.

**Comment by jhprinz** [comment]
there is a Alanine example notebook. But it basically boils down to this:

``` py
import openpathsampling as paths

# open for storage for appending
storage = paths.Storage("filename.nc", "a")

# create new PathSampling object
mstis_calc = paths.PathSampling(
    storage=storage,
    sample_set=storage.steps.last.active,  # from the last step pick the _active_ sampleset
    move_scheme=storage.schemes[0]  # we want to simulate move scheme[0]
)

# continue the simulation for 100 steps
mstis_calc.run(100)

# and properly close
storage.close()
```

if you have stored more than one move scheme you need to load the one you want. You can store it with a name, when you name it _before_ you save it.

``` py
move_scheme.name = 'MyScheme'
storage.save(move_scheme)
```

This is approach is a little unsafe because you could trick the system into having to objects with the same UUID but different names. But it is only a name to simplify loading

``` py
mstis_calc = paths.PathSampling(
    storage=storage,
    sample_set=storage.steps.last.active,  # from the last step pick the _active_ sampleset
    move_scheme=storage.schemes['MyScheme']  # reload `MoveScheme`
)
```

**Comment by dwhswenson** [comment]
@jhprinz : is there a reason that reloading the `PathSampling` object can't work? (Maybe you can't store the correct value of `steps`?) I remember that I tried to just reload the `PathSampling` object from a previous calculation once, and it didn't work.

**Comment by jhprinz** [comment]
Yes, the PathSampling object is not immutable. It changes its internal state, i.e. the `sample_set` and `step`, etc... If you would like to save it, you would need to resave it all the same to keep it updated. Or be more precise, which state of the PathSampling object do you want to save or load? After each iteration it is practically a different object.

Usually people just overwrote the objects, like in a database. But since we work strictly with immutable objects you need to build a new one with the state you want to start from.

Still you should be able to save and load it, but you will get the object back from the point where you first saved it. If that did not work, i am a little puzzled and need to have a closer look.

**Comment by dwhswenson** [comment]
I would have to try again, but I seem to remember something fundamentally not working (like, errors on trying to load). But the main value would be in being able to use the `.run_until` function, which becomes kind of meaningless if you can't re-load the internal state. So unless that works, I think we should discourage re-loading of `PathSampling` objects.

I think the concepts of "changing internal state" and "immutable objects" would be confusing for a user who is not an experienced programmer. Forbidding them from reloading the object is easier than trying to explain why it doesn't work the way they expected! :-)

**Comment by sonyahanson** [comment]
Currently trying to run this so I can get an idea of how to run OPS on a protein-ligand system. Is this PR essential?

**Comment by jchodera** [comment]
As far as I know, this PR contains essential fixes to the scripts to allow this to work with the current API of openpathsampling as of 19 Sep 2016. I have no idea if the API has changed again since then to cause this to break again.

I'd suggest merging the PR and continuing on in a separate PR.

**Comment by dwhswenson** [comment]
Glancing over the PRs merged since 19 Sept, I didn't see anything that would change the API (we're mostly API-locked now, although already including deprecations -- for practical purposes, I think we're set to 1.0, because OPS is already being used in other projects.)

@sonyahanson : I second @jchodera's suggestion to merge and build on it in a second PR. If anything doesn't run correctly, let me know, and I should be able to quickly track down the API change.

**Comment by sonyahanson** [comment]
Great, thanks! Will do. Merging.

**Pull request merged**
